conduit.api.cors.headers=Authorization, Content-Type
conduit.api.cors.origin=http://localhost:8080
conduit.server.port=8081
conduit.database.file=~/janilla/sample-data/conduit.db
conduit.database.seed=true
conduit.jwt.key=secretkey
conduit.live-demo=false
