conduit.api.cors.headers=Authorization, Content-Type
conduit.api.cors.origin=https://localhost:8443
conduit.server.keystore.password=password
conduit.server.keystore.path=~/janilla/localhost
conduit.server.port=8444
conduit.database.file=~/janilla/sample-data/conduit.db
conduit.database.seed=true
conduit.jwt.key=secretkey
conduit.live-demo=false
