acme-dashboard.api.cors.origin=https://acmedashboard.janilla.local:8443
acme-dashboard.live-demo=true

address-book.api.cors.origin=https://addressbook.janilla.local:8443
address-book.live-demo=true

blank-template.api.cors.origin=https://blanktemplate.janilla.local:8443
blank-template.live-demo=true

ecommerce-template.api.cors.origin=https://ecommercetemplate.janilla.local:8443
ecommerce-template.live-demo=true

janilla-com.api.cors.headers=Content-Type
janilla-com.api.cors.origin=https://janilla.local:8443
janilla-com.api.url=https://janilla.local:8444/api
janilla-com.authority=janilla.local:8444
janilla-com.database.file=~/janilla/sample-data/janilla-com.db
janilla-com.jwt.cookie=janilla-token
janilla-com.jwt.key=secretkey
janilla-com.live-demo=true
janilla-com.mail.host=smtp.example.com
janilla-com.mail.password=password
janilla-com.mail.port=465
janilla-com.mail.username=foo.bar@example.com
janilla-com.server.keystore.common-name=*.janilla.local
janilla-com.server.keystore.password=password
janilla-com.server.keystore.path=~/janilla/janilla.local
janilla-com.server.keystore.subject-alternative-name=dns:janilla.local,ip:127.0.0.1,dns:acmedashboard.janilla.local,dns:addressbook.janilla.local,dns:blanktemplate.janilla.local,dns:conduit.janilla.local,dns:ecommercetemplate.janilla.local,dns:petclinic.janilla.local,dns:todomvc.janilla.local,dns:websitetemplate.janilla.local
janilla-com.server.port=8444
janilla-com.upload.directory=~/janilla/sample-data/janilla-com-upload

petclinic.live-demo=true

website-template.api.cors.origin=https://websitetemplate.janilla.local:8443
website-template.live-demo=true
