address-book.api.cors.headers=Content-Type
address-book.api.cors.origin=http://localhost:8080
address-book.server.port=8081
address-book.database.file=~/janilla/sample-data/address-book.db
address-book.live-demo=false
