<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>janilla-petclinic-test</artifactId>
	<dependencies>
		<dependency>
			<groupId>com.janilla</groupId>
			<artifactId>janilla-blank-template-test</artifactId>
			<version>${revision}</version>
		</dependency>
		<dependency>
			<groupId>com.janilla</groupId>
			<artifactId>janilla-petclinic-fullstack</artifactId>
			<version>${revision}</version>
		</dependency>
	</dependencies>
	<parent>
		<groupId>com.janilla</groupId>
		<artifactId>janilla-petclinic</artifactId>
		<version>${revision}</version>
		<relativePath>..</relativePath>
	</parent>
	<properties>
		<exec.mainClass>com.janilla.petclinic.test.PetclinicTest</exec.mainClass>
	</properties>
	<name>janilla-petclinic-test</name>
	<description>Janilla Petclinic Test</description>
	<profiles>
		<profile>
			<id>execute</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<configuration>
							<executable>java</executable>
							<arguments>
								<argument>--module-path</argument>
								<modulepath />
								<argument>--module</argument>
								<argument>com.janilla.petclinic.test/com.janilla.petclinic.test.PetclinicTest</argument>
							</arguments>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
