blank-template.api.url=http://localhost:8081/api
blank-template.download.directory=~/janilla/download
blank-template.jwt.cookie=blank-token
blank-template.jwt.key=secretkey
blank-template.server.port=8080
