acme-dashboard.api.url=http://acmedashboard.janilla.local:8081/api

address-book.api.url=http://addressbook.janilla.local:8081/api

blank-template.api.url=http://blanktemplate.janilla.local:8081/api

conduit.api.url=http://conduit.janilla.local:8081/api

ecommerce-template.api.url=http://ecommercetemplate.janilla.local:8081/api

janilla-com.api.url=http://janilla.local:8081/api
janilla-com.authority=janilla.local:8080
janilla-com.download.directory=~/janilla/download
janilla-com.jwt.key=secretkey
#janilla-com.server.keystore.common-name=*.janilla.local
#janilla-com.server.keystore.password=password
#janilla-com.server.keystore.path=~/janilla/janilla.local
#janilla-com.server.keystore.subject-alternative-name=dns:janilla.local,ip:127.0.0.1,dns:acmedashboard.janilla.local,dns:addressbook.janilla.local,dns:blanktemplate.janilla.local,dns:conduit.janilla.local,dns:ecommercetemplate.janilla.local,dns:petclinic.janilla.local,dns:todomvc.janilla.local,dns:websitetemplate.janilla.local
janilla-com.server.port=8080
janilla-com.title=Janilla.com

petclinic.api.url=http://petclinic.janilla.local:8081/api

website-template.api.url=http://websitetemplate.janilla.local:8081/api
