acme-dashboard.api.url=https://acmedashboard.janilla.local:8444/api

address-book.api.url=https://addressbook.janilla.local:8444/api

blank-template.api.url=https://blanktemplate.janilla.local:8444/api

conduit.api.url=https://conduit.janilla.local:8444/api

ecommerce-template.api.url=https://ecommercetemplate.janilla.local:8444/api

janilla-com.api.url=https://janilla.local:8444/api
janilla-com.authority=janilla.local:8443
janilla-com.download.directory=~/janilla/download
janilla-com.jwt.key=secretkey
janilla-com.server.keystore.common-name=*.janilla.local
janilla-com.server.keystore.password=password
janilla-com.server.keystore.path=~/janilla/janilla.local
janilla-com.server.keystore.subject-alternative-name=dns:janilla.local,ip:127.0.0.1,dns:acmedashboard.janilla.local,dns:addressbook.janilla.local,dns:blanktemplate.janilla.local,dns:conduit.janilla.local,dns:ecommercetemplate.janilla.local,dns:petclinic.janilla.local,dns:todomvc.janilla.local,dns:websitetemplate.janilla.local
janilla-com.server.port=8443
janilla-com.title=Janilla.com

petclinic.api.url=https://petclinic.janilla.local:8444/api

website-template.api.url=https://websitetemplate.janilla.local:8444/api
