acme-dashboard.api.cors.headers=
acme-dashboard.api.cors.origin=
acme-dashboard.api.url=https://acmedashboard.janilla.local:8443/api
acme-dashboard.jwt.key=secretkey
acme-dashboard.server.keystore.password=password
acme-dashboard.server.keystore.path=~/janilla/janilla.local

address-book.api.cors.headers=
address-book.api.cors.origin=
address-book.api.url=https://addressbook.janilla.local:8443/api
address-book.server.keystore.password=password
address-book.server.keystore.path=~/janilla/janilla.local

blank-template.api.cors.headers=
blank-template.api.cors.origin=
blank-template.api.url=https://blanktemplate.janilla.local:8443/api
blank-template.jwt.key=secretkey
blank-template.server.keystore.password=password
blank-template.server.keystore.path=~/janilla/janilla.local
blank-template.upload.directory=~/janilla/sample-data/blank-template-upload

conduit.api.cors.headers=
conduit.api.cors.origin=
conduit.api.url=https://conduit.janilla.local:8443/api
conduit.database.seed=true
conduit.jwt.key=secretkey

ecommerce-template.api.cors.headers=
ecommerce-template.api.cors.origin=
ecommerce-template.api.url=https://ecommercetemplate.janilla.local:8443/api
ecommerce-template.jwt.key=secretkey
ecommerce-template.server.keystore.password=password
ecommerce-template.server.keystore.path=~/janilla/janilla.local
ecommerce-template.stripe.publishable-key=pk_test_
ecommerce-template.stripe.secret-key=sk_test_
ecommerce-template.stripe.webhooks-signing-secret=whsec_
ecommerce-template.upload.directory=~/janilla/sample-data/ecommerce-template-upload

janilla-com.api.url=https://janilla.local:8443/api
janilla-com.authority=janilla.local:8443
janilla-com.server.keystore.common-name=*.janilla.local
janilla-com.server.keystore.password=password
janilla-com.server.keystore.path=~/janilla/janilla.local
janilla-com.server.keystore.subject-alternative-name=dns:janilla.local,ip:127.0.0.1,dns:acmedashboard.janilla.local,dns:addressbook.janilla.local,dns:blanktemplate.janilla.local,dns:conduit.janilla.local,dns:ecommercetemplate.janilla.local,dns:petclinic.janilla.local,dns:todomvc.janilla.local,dns:websitetemplate.janilla.local
janilla-com.server.port=8443

petclinic.api.url=https://petclinic.janilla.local:8443/api
petclinic.server.keystore.password=password
petclinic.server.keystore.path=~/janilla/janilla.local

website-template.api.cors.headers=
website-template.api.cors.origin=
website-template.api.url=https://websitetemplate.janilla.local:8443/api
website-template.jwt.key=secretkey
website-template.mail.host=smtp.example.com
website-template.mail.port=465
website-template.mail.username=foo.bar@example.com
website-template.mail.password=password
website-template.server.keystore.password=password
website-template.server.keystore.path=~/janilla/janilla.local
website-template.upload.directory=~/janilla/sample-data/website-template-upload
