blank-template.api.cors.headers=Content-Type
blank-template.api.cors.origin=http://localhost:8080
blank-template.api.url=http://localhost:8081/api
blank-template.server.port=8081
blank-template.database.file=~/janilla/sample-data/blank-template.db
blank-template.jwt.cookie=blank-token
blank-template.jwt.key=secretkey
blank-template.live-demo=false
blank-template.upload.directory=~/janilla/sample-data/blank-template-upload
