website-template.api.url=https://localhost:8444/api
website-template.download.directory=~/janilla/download
website-template.jwt.cookie=website-token
website-template.jwt.key=secretkey
website-template.server.keystore.password=password
website-template.server.keystore.path=~/janilla/localhost
website-template.server.port=8443
website-template.title=Janilla Website Template
