website-template.api.url=http://localhost:8081/api
website-template.download.directory=~/janilla/download
website-template.jwt.cookie=website-token
website-template.jwt.key=secretkey
website-template.server.port=8080
website-template.title=Janilla Website Template
