conduit.api.cors.headers=
conduit.api.cors.origin=
conduit.api.url=https://localhost:8443/api
conduit.server.keystore.password=password
conduit.server.keystore.path=~/janilla/localhost
conduit.server.port=8443
