website-template.api.cors.headers=Content-Type
website-template.api.cors.origin=http://localhost:8080
website-template.api.url=http://localhost:8081/api
website-template.server.port=8081
website-template.database.file=~/janilla/sample-data/website-template.db
website-template.jwt.cookie=website-token
website-template.jwt.key=secretkey
website-template.live-demo=false
website-template.mail.host=smtp.example.com
website-template.mail.port=465
website-template.mail.username=foo.bar@example.com
website-template.mail.password=password
website-template.upload.directory=~/janilla/sample-data/website-template-upload
