ecommerce-template.api.url=http://localhost:8081/api
ecommerce-template.download.directory=~/janilla/download
ecommerce-template.jwt.cookie=ecommerce-token
ecommerce-template.jwt.key=secretkey
ecommerce-template.server.port=8080
ecommerce-template.stripe.publishable-key=pk_test_
ecommerce-template.stripe.url=http://js.stripe.com/clover/stripe.js
ecommerce-template.title=Janilla Ecommerce Template
